import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-blue-600 text-white p-4">
          <nav className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">Mi Aplicación</h1>
            <div className="flex gap-4">
              <Link href="/" className="hover:underline">
                Inicio
              </Link>
              <span>|</span>
              <Link
                href="/blog/introduccion-nextjs-15"
                className="hover:underline"
              >
                blog 1
              </Link>
              <span>|</span>
              <Link
                href="/blog/react-server-components"
                className="hover:underline"
              >
                blog 2
              </Link>
              <span>|</span>
              <Link href="/dashboard" className="hover:underline">
                Dashboard
              </Link>
              <span>|</span>
              <Link href="/products" className="hover:underline">
                Productos
              </Link>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
